# Generated by Django 5.2.4 on 2025-08-06 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="creation_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="last_update_date",
            field=models.DateField(auto_now=True),
        ),
    ]
