# Generated by Django 5.2.4 on 2025-08-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0004_favoritearticle"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content_parsed",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_parsed",
            field=models.TextField(blank=True),
        ),
    ]
