# Generated by Django 5.2.4 on 2025-08-07 18:50

from django.db import migrations
from markdown import markdown


def parse_markdown_for_existing_articles(apps, schema_editor):
    Article = apps.get_model("blog_app", "Article")
    for article in Article.objects.all():
        article.title_parsed = markdown(article.title, extensions=["extra"])[3:-4]
        article.content_parsed = markdown(article.content, extensions=["extra"])
        article.save()


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0005_article_content_parsed_article_title_parsed"),
    ]

    operations = [
        migrations.RunPython(parse_markdown_for_existing_articles),
    ]
