# Generated by Django 5.2.4 on 2025-08-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_auto_20250807_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title_parsed',
        ),
    ]
