# Generated by Django 5.2.4 on 2025-08-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_remove_article_title_parsed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog_app.articletag'),
        ),
    ]
